/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import thread.ServerThread;

/**
 *
 * @author nikol
 */
public class FrmConfiguration extends javax.swing.JFrame {

    private final ResourceBundle resourceBundle;

    /**
     * Creates new form FrmServer
     */
    public FrmConfiguration() {
        initComponents();
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JPasswordField();
        lblConfiguration = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtServerPort = new javax.swing.JTextField();
        lblServerPort = new javax.swing.JLabel();
        lblDriver = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtURL = new javax.swing.JTextField();
        lblURL = new javax.swing.JLabel();
        btnCustom = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBackground(new java.awt.Color(51, 52, 57));
        txtPassword.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 300, -1));

        lblConfiguration.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblConfiguration.setForeground(new java.awt.Color(255, 255, 255));
        lblConfiguration.setText("Configuration");
        getContentPane().add(lblConfiguration, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        btnConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/connect.png"))); // NOI18N
        btnConnect.setBorderPainted(false);
        btnConnect.setContentAreaFilled(false);
        btnConnect.setEnabled(false);
        btnConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnectMouseClicked(evt);
            }
        });
        getContentPane().add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        lblPassword.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(119, 118, 116));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 73));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 300, -1));

        lblUsername.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        txtUsername.setEditable(false);
        txtUsername.setBackground(new java.awt.Color(51, 52, 57));
        txtUsername.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);
        txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsername.setSelectionColor(new java.awt.Color(119, 118, 116));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 300, -1));

        jSeparator4.setBackground(new java.awt.Color(119, 118, 116));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 73));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 300, -1));

        jSeparator1.setBackground(new java.awt.Color(119, 118, 116));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 73));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 300, -1));

        txtServerPort.setEditable(false);
        txtServerPort.setBackground(new java.awt.Color(51, 52, 57));
        txtServerPort.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtServerPort.setForeground(new java.awt.Color(255, 255, 255));
        txtServerPort.setBorder(null);
        txtServerPort.setCaretColor(new java.awt.Color(255, 255, 255));
        txtServerPort.setSelectionColor(new java.awt.Color(119, 118, 116));
        getContentPane().add(txtServerPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 300, -1));

        lblServerPort.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblServerPort.setForeground(new java.awt.Color(255, 255, 255));
        lblServerPort.setText("Server port");
        getContentPane().add(lblServerPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        lblDriver.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblDriver.setText("Driver");
        getContentPane().add(lblDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        txtDriver.setEditable(false);
        txtDriver.setBackground(new java.awt.Color(51, 52, 57));
        txtDriver.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtDriver.setForeground(new java.awt.Color(255, 255, 255));
        txtDriver.setBorder(null);
        txtDriver.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDriver.setSelectionColor(new java.awt.Color(119, 118, 116));
        getContentPane().add(txtDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 300, -1));

        jSeparator2.setBackground(new java.awt.Color(119, 118, 116));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 73));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 300, -1));

        jSeparator3.setBackground(new java.awt.Color(119, 118, 116));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 73));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 300, -1));

        txtURL.setEditable(false);
        txtURL.setBackground(new java.awt.Color(51, 52, 57));
        txtURL.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        txtURL.setForeground(new java.awt.Color(255, 255, 255));
        txtURL.setBorder(null);
        txtURL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtURL.setSelectionColor(new java.awt.Color(119, 118, 116));
        getContentPane().add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 300, -1));

        lblURL.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblURL.setForeground(new java.awt.Color(255, 255, 255));
        lblURL.setText("URL");
        getContentPane().add(lblURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        btnCustom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/custom.png"))); // NOI18N
        btnCustom.setBorderPainted(false);
        btnCustom.setContentAreaFilled(false);
        btnCustom.setFocusPainted(false);
        btnCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomMouseClicked(evt);
            }
        });
        getContentPane().add(btnCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, 40));

        btnDefault.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/default.png"))); // NOI18N
        btnDefault.setBorderPainted(false);
        btnDefault.setContentAreaFilled(false);
        btnDefault.setFocusPainted(false);
        btnDefault.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDefaultMouseClicked(evt);
            }
        });
        getContentPane().add(btnDefault, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 120, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-gray.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-server.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefaultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDefaultMouseClicked
        try {
            Controller.getInstance().setDefaultConfig(true);
            Properties properties = Controller.getInstance().readPropertiesFile();

            txtServerPort.setEditable(false);
            jSeparator1.setBackground(new Color(119, 118, 116));
            txtDriver.setEditable(false);
            jSeparator2.setBackground(new Color(119, 118, 116));
            txtURL.setEditable(false);
            jSeparator3.setBackground(new Color(119, 118, 116));
            txtUsername.setEditable(false);
            jSeparator4.setBackground(new Color(119, 118, 116));
            txtPassword.setEditable(false);
            jSeparator5.setBackground(new Color(119, 118, 116));

            txtServerPort.setText(properties.getProperty("default_serverPort"));
            txtDriver.setText(properties.getProperty("default_driverDatabase"));
            txtURL.setText(properties.getProperty("default_urlDatabase"));
            txtUsername.setText(properties.getProperty("default_userDatabase"));
            txtPassword.setText(properties.getProperty("default_passwordDatabase"));
            btnConnect.setEnabled(true);

        } catch (IOException ex) {
            MessageDialog.showErrorMessage(null, resourceBundle.getString("server_file_error"),
                    resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnDefaultMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomMouseClicked
        Controller.getInstance().setDefaultConfig(false);

        txtServerPort.setEditable(true);
        txtServerPort.requestFocus();
        jSeparator1.setBackground(new Color(255, 255, 255));
        txtDriver.setEditable(true);
        jSeparator2.setBackground(new Color(255, 255, 255));
        txtURL.setEditable(true);
        jSeparator3.setBackground(new Color(255, 255, 255));
        txtUsername.setEditable(true);
        jSeparator4.setBackground(new Color(255, 255, 255));
        txtPassword.setEditable(true);
        jSeparator5.setBackground(new Color(255, 255, 255));
        btnConnect.setEnabled(true);

        txtServerPort.setText("");
        txtDriver.setText("");
        txtURL.setText("");
        txtUsername.setText("");
        txtPassword.setText("");

    }//GEN-LAST:event_btnCustomMouseClicked

    private void btnConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnectMouseClicked
        try {
            if (!Controller.getInstance().isDefaultConfig()) {
                Controller.getInstance().writeIntoPropertiesFile(txtServerPort.getText(), txtDriver.getText(),
                        txtURL.getText(), txtUsername.getText(), txtPassword.getText());
            }

            ServerThread serverThread = new ServerThread();
            serverThread.start();

            MessageDialog.showSuccessMessage(null, resourceBundle.getString("server_connected_successfully"),
                    resourceBundle.getString("success_title"));
            new FrmControlPanel(serverThread).setVisible(true);
            dispose();
        } catch (IOException ex) {
            MessageDialog.showErrorMessage(null, resourceBundle.getString("server_connected_error"),
                    resourceBundle.getString("error_title"));
        }
    }//GEN-LAST:event_btnConnectMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnCustom;
    private javax.swing.JButton btnDefault;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblConfiguration;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblServerPort;
    private javax.swing.JLabel lblURL;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtServerPort;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        URL imageUrl = ClassLoader.getSystemResource("img/transportation.png");
        ImageIcon imageIcon = new ImageIcon(imageUrl);
        setIconImage(imageIcon.getImage());

        setBackground(new Color(0, 0, 0, 0));
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dimension.width / 2 - this.getSize().width / 2, dimension.height / 2 - this.getSize().height / 2);

        lblConfiguration.setText(resourceBundle.getString("server_lbl_configuration") + ":");
        Controller.getInstance().setIconToButton("img/" + resourceBundle.getString("server_btn_default") + ".png", btnDefault);
        Controller.getInstance().setIconToButton("img/" + resourceBundle.getString("server_btn_custom") + ".png", btnCustom);
        lblServerPort.setText(resourceBundle.getString("server_lbl_port") + ":");
        lblDriver.setText(resourceBundle.getString("server_lbl_driver") + ":");
        lblURL.setText(resourceBundle.getString("server_lbl_URL") + ":");
        lblUsername.setText(resourceBundle.getString("server_lbl_username") + ":");
        lblPassword.setText(resourceBundle.getString("server_lbl_password") + ":");
        Controller.getInstance().setIconToButton("img/" + resourceBundle.getString("server_btn_connect") + ".png", btnConnect);
        Controller.getInstance().setIconToButton("img/" + resourceBundle.getString("server_btn_cancel") + ".png", btnCancel);
    }
}
