/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import listeners.ClientsListener;
import thread.CheckNewClientsThread;
import thread.ClientHandlerThread;
import thread.ServerThread;
import view.tablemodels.TableModelSocket;

/**
 *
 * @author nikol
 */
public final class FrmControlPanel extends javax.swing.JFrame implements ClientsListener {

    private ServerThread serverThread;
    private TableModelSocket tms;
    private CheckNewClientsThread checkNewClientsThread;
    private ResourceBundle resourceBundle;

    /**
     * Creates new form FrmControlPanel
     * @param serverThread
     */
    public FrmControlPanel(ServerThread serverThread) {
        initComponents();
        this.serverThread = serverThread;
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConnections = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnKick = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(119, 118, 116));

        tableConnections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableConnections);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 260));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);

        btnStart.setBackground(new java.awt.Color(51, 52, 57));
        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start-button.png"))); // NOI18N
        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnStart.setEnabled(false);
        btnStart.setFocusPainted(false);
        btnStart.setIconTextGap(10);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnKick.setBackground(new java.awt.Color(51, 52, 57));
        btnKick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKick.setForeground(new java.awt.Color(255, 255, 255));
        btnKick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kick.png"))); // NOI18N
        btnKick.setText("Kick");
        btnKick.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnKick.setFocusPainted(false);
        btnKick.setIconTextGap(10);
        btnKick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKickActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(51, 52, 57));
        btnStop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stop.png"))); // NOI18N
        btnStop.setText("Stop");
        btnStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnStop.setFocusPainted(false);
        btnStop.setIconTextGap(10);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnKick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnKick, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 200, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chad-kirchoff-xe-e69j6-Ds-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 622, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (!serverThread.isAlive()) {
            try {
                serverThread = new ServerThread();
                serverThread.start();
                checkNewClientsThread = new CheckNewClientsThread(serverThread, tms);
                checkNewClientsThread.start();
                btnStart.setEnabled(false);
                btnStop.setEnabled(true);
                btnKick.setEnabled(true);
            } catch (IOException ex) {
                MessageDialog.showErrorMessage(null, resourceBundle.getString("server_connected_error"),
                        resourceBundle.getString("error_title"));
            }
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (serverThread.isAlive()) {
            try {
                serverThread.stopServerThread();
                checkNewClientsThread.interrupt();
                btnStart.setEnabled(true);
                btnStop.setEnabled(false);
                btnKick.setEnabled(false);
            } catch (IOException ex) {
                MessageDialog.showErrorMessage(null, resourceBundle.getString("server_stop_problem"),
                        resourceBundle.getString("error_title"));
            }
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnKickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKickActionPerformed
        int selectedRow = tableConnections.getSelectedRow();

        if (selectedRow != -1) {
            try {
                ClientHandlerThread client = serverThread.getClients().get(selectedRow);
                client.getSocket().close();
            } catch (IOException ex) {
                MessageDialog.showErrorMessage(null, resourceBundle.getString("server_kick_problem"),
                        resourceBundle.getString("error_title"));
            }
        }
    }//GEN-LAST:event_btnKickActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKick;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableConnections;
    // End of variables declaration//GEN-END:variables

    public void preparePanel() {
        resourceBundle = ResourceBundle.getBundle("props/LanguageBundle", Controller.getInstance().getLocale());

        btnStart.setText(resourceBundle.getString("server_btn_start"));
        btnKick.setText(resourceBundle.getString("server_btn_kick"));
        btnStop.setText(resourceBundle.getString("server_btn_stop"));

        URL imageUrl = ClassLoader.getSystemResource("img/transportation.png");
        ImageIcon icon = new ImageIcon(imageUrl);
        setIconImage(icon.getImage());

        setLocationRelativeTo(null);
        serverThread.addListener(this);
        tms = new TableModelSocket(serverThread.getClients());
        tableConnections.setModel(tms);
        checkNewClientsThread = new CheckNewClientsThread(serverThread, tms);
        checkNewClientsThread.start();
    }

    public void clearPanel() {
        tms.updateTable(new ArrayList<>());
    }

    @Override
    public void onClientConnected() {
        tms.updateTable(serverThread.getClients());
    }

}
