package view;

import controller.Controller;
import java.net.URL;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 * @author nikol
 */
public class FrmLanguage extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLanguage() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblIconUK = new javax.swing.JLabel();
        lblIconRS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 200));
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));
        getContentPane().add(jPanel1);
        getContentPane().add(jPanel3);

        lblIconUK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-great-britain-96.png"))); // NOI18N
        lblIconUK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconUKMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconUK);

        lblIconRS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconRS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-serbia-96.png"))); // NOI18N
        lblIconRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconRSMouseClicked(evt);
            }
        });
        getContentPane().add(lblIconRS);
        getContentPane().add(jPanel2);
        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconRSMouseClicked
        Controller.getInstance().setLocale(new Locale("sr", "RS"));
        new FrmConfiguration().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblIconRSMouseClicked

    private void lblIconUKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconUKMouseClicked
        Controller.getInstance().setLocale(new Locale("en", "UK"));
        new FrmConfiguration().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblIconUKMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblIconRS;
    private javax.swing.JLabel lblIconUK;
    // End of variables declaration//GEN-END:variables

    /**
     * Method for preparing form for use.
     */
    private void prepareView() {
        URL imageUrl = ClassLoader.getSystemResource("img/transportation.png");
        ImageIcon icon = new ImageIcon(imageUrl);
        setIconImage(icon.getImage());
        setLocationRelativeTo(null);
        pack();
        Controller.getInstance().setIconToLabel("img/icons8-great-britain-96.png", lblIconUK);
        Controller.getInstance().setIconToLabel("img/icons8-serbia-96.png", lblIconRS);
        this.setTitle("Choose language");
    }
}
